apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j2aii5li8-java-quarkus
  janus-idp.io/tekton: j2aii5li8-java-quarkus
  backstage.io/kubernetes-id: j2aii5li8-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j2aii5li8-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
